dist: trusty
sudo: required

language: python
python:
  - "3.6"

#cache:
#    directories:
#    - bin #cache .weights files
    
# command to install dependencies
install: 
    - pip install pytest
    - pip install -e .

# command to run tests
script: pytest main.py

#Upload code coverage statistics
#after_success:
#  - codecov