dist: trusty
sudo: required

language: python
python:
  - "3.5"

#cache:
#    directories:
#    - bin #cache .weights files
    
# command to install dependencies
install: 
    - pip install pytest

# command to run tests
script: python tests/main.py

#Upload code coverage statistics
#after_success:
#  - codecov