dist: trusty
sudo: required

language: python
python:
  - "3.5"

#cache:
#    directories:
#    - bin #cache .weights files
    
# command to install dependencies
install: 
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=3.5 anaconda=4.4.0
  - source activate test-env
  - pip install tensorflow==1.2.1
  - pip install keras==2.0.8
  - pip install opencv-python
  - pip install tqdm
  - pip install imgaug
  - pip install pytest-cov
  - pip install -e .

# command to run tests
script: pytest -x --cov=./

#Upload code coverage statistics
#after_success:
#  - codecov






